### ISSUE TITLE
only gh-pages branch as primary branch

### ISSUE THREAD

**Issue by brunobord** [n1k0/kept#11]
I think you'd get instant result by only having one branch, the `gh-pages`branch. By committing / pushing on this branch only, the latest modifications would instantly be published on http://n1k0.github.io/kept/, without having to merge from `master`.

I've done it on [several](https://github.com/brunobord/mdwrangler) [other](https://github.com/brunobord/relax) [projects](https://github.com/brunobord/pomodorock). It just works.

**Comment by n1k0** [comment]
Yup I've used that trick in the past, but as we're moving towards using a build system (see #10), that probably won't work. I'll just create a script for updating the `gh-pages` branch :)

As a side note, I would love avoiding to rely on a build system, but that's the price to pay with react…

**Comment by brunobord** [comment]
mmm... AFAICT, [travis](https://travis-ci.org/) could do this for you, too.

**Comment by n1k0** [comment]
Lemme just write tests first ;)

**Comment by n1k0** [comment]
(oh, I see what you did there. Smart.)

**Comment by brunobord** [comment]
I'm not talking about tests, it's travis CI, as Continuous Integration: see https://medium.com/philosophy-logic/53a8270e87db

**Comment by n1k0** [comment]
Definitely smart. Will do. Can you please file an issue for this? :)
