### ISSUE TITLE
Provide a simple way to build/serve the project

### ISSUE THREAD

**Issue by n1k0** [n1k0/kept#7]
- [x] transpilation
- [x] concatenation
- [x] minification
- [x] watch
- [x] serve

**Comment by MoOx** [comment]
You should take a look to https://github.com/putaindecode/website/
Especially https://github.com/putaindecode/website/blob/master/Gulpfile.js & https://github.com/putaindecode/website/tree/master/tasks
Maybe use browserify(concat replacement with following transformations: es6ify (transpilation) + uglifyify (minification))

**Comment by chadrien** [comment]
:+1: for gulp

**Comment by n1k0** [comment]
Partially fixed with #13, thanks @lionelB!

**Comment by lionelB** [comment]
Great!

**Comment by lionelB** [comment]
Actually, the build system packed the kept sources with vendors (react and react components)
which increase build time when only kept source files are modified.
Are you interested in refactoring build system in a way it'll produce a vendor bundle and a kept bundle.
To do that we can use browserify.external() 

Of course I'm interested in doing that!

**Comment by n1k0** [comment]
> Of course I'm interested in doing that!

Go! :)

**Comment by n1k0** [comment]
Take care to file a new issue for that though.

**Comment by lionelB** [comment]
```
$ git branch
  feat/10-add-gulpfile
  fix/Handle-submit-properly-in-KeptTodoForm
* fix/separate-bundle-into-vendor-and-kept
  master
```

I've already created a branch, I'll fill a proper issue too!

**Comment by n1k0** [comment]
Oh sure, you can directly submit a PR when you're done, that works too :)
