### ISSUE TITLE
Improve UX for draggable panels

### ISSUE THREAD

**Issue by n1k0** [n1k0/kept#9]
The silly CSS columns trick is not very usable, we need to find something better.

http://gridster.net/ seems neat but probably too fancy, and relies on jQuery…

**Comment by n1k0** [comment]
Wondering about https://github.com/desandro/masonry too… but no obvious support for dragging though.

**Comment by n1k0** [comment]
js based solutions seems to suck… we should look at the flex box model http://the-echoplex.net/flexyboxes/

**Comment by lionelB** [comment]
Perhaps I miss the point of Flexbox but i think it doesn't solve our problem, since we need to create flex container by hand depending on the available width as it will be the case if we want to sort of masonry. 
FlexBox could be helpful to order by colum, thought
I 'll investigate to handle column by hand

**Comment by n1k0** [comment]
Yeah, the flex box model 1. sucks balls and 2. doesn't solve our current issue.

I think this asks for a js based solution (sadly).

**Comment by lionelB** [comment]
I ´ll investigate http://demosthenes.info/blog/844/Easy-Masonry-Layout-With-Flexbox

**Comment by lionelB** [comment]
previous link suffers form the same problem as our current solution. Elements are distributed by row and after by column (which is strange for ordering). if we want masonry like layout with element distributed to columns first, I'm afraid that only js can do that...

**Comment by n1k0** [comment]
Maybe what we actually want is trello-style columns?
